// $('p:first').css('border', '1px solid red');
// $('p:last').css('border', '1px solid red');
// $('a:eq(2)').css('border', '1px solid red');
// $('*:not(h2,p)').css('border', '1px solid red');
// $('li:odd').css('border', '1px solid red');
// $('li:even').css('border', '1px solid red');
// $('li:gt(0)').css('border', '1px solid red');
// $('li:lt(3)').css('border', '1px solid red');
// $('*:header').css('border', '1px solid red');
// $('li:animated').css('border', '1px solid red');
// $('li:hidden').css('border', '1px solid red');
// $('li:visible').css('border', '1px solid red');
$('li:lang(ru)').css('border', '1px solid red');